### ISSUE TITLE
failed to load index.html in Windows

### ISSUE THREAD

**Issue by notizklotz** [michherren/waldkauz#1]
Version 0.0.7 doesn't start properly on Windows 10:

```
$ ./waldkauz-debug.exe
{"level":"info","ts":"2022-08-31T09:25:17.554+0200","msg":"started Redpanda Console","version":"development","built_at":
"<not set>"}
{"level":"info","ts":"2022-08-31T09:25:17.554+0200","msg":"connecting to Kafka seed brokers, trying to fetch cluster met
adata"}
{"level":"info","ts":"2022-08-31T09:25:17.654+0200","msg":"successfully connected to kafka cluster","advertised_broker_c
ount":5,"topic_count":9,"controller_id":4,"kafka_version":"v3.0"}
{"level":"info","ts":"2022-08-31T09:25:17.655+0200","msg":"creating schema registry client and testing connectivity"}
{"level":"info","ts":"2022-08-31T09:25:17.767+0200","msg":"successfully tested schema registry connectivity"}
{"level":"info","ts":"2022-08-31T09:25:17.767+0200","msg":"creating Kafka connect HTTP clients and testing connectivity
to all clusters"}
{"level":"info","ts":"2022-08-31T09:25:17.767+0200","msg":"tested Kafka connect cluster connectivity","successful_cluste
rs":0,"failed_clusters":0}
{"level":"info","ts":"2022-08-31T09:25:17.767+0200","msg":"successfully create Kafka connect service"}
{0x69fe2e0}
{"level":"fatal","ts":"2022-08-31T09:25:18.104+0200","msg":"failed to load index.html from embedded filesystem","error":
"open index.html: file does not exist"}
```

**Comment by michherren** [comment]
I could not reproduce this on Windows (win11):

![image](https://user-images.githubusercontent.com/1235637/188012309-b22c546c-8213-44cd-84ab-3067e665db1e.png)

Is it possible you used a config.yaml from an earlier version?  There were some breaking changes in the latest releases related to asset loading. For example ServeFrontend has to be false because the waldkauz-wrapper handles the file embedding instead of Redpanda console. 

Maybe regenerating the config.yaml template helps: Just rename the waldkauz-data folder and run waldkauz-debug.exe again. Then copy the kafka connection-details to the new config.yaml and test again.

**Comment by notizklotz** [comment]
My bad. I just copied a config file for Redpanda Console 2.0.2 and it doesn't work. If a edit the template generated by Waldkauz it works. sorry!
